apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: spark-pi-example-{{ ts_nodash }}          # <-- Tên CỐ ĐỊNH, KHÔNG để generateName, và khớp với application_name trong sensor
  namespace: spark-jobs
spec:
  type: Scala
  mode: cluster
  image: "acrmlfoteaidev.azurecr.io/spark-py-job:v1"
  imagePullPolicy: Always
  mainClass: org.apache.spark.examples.SparkPi
  mainApplicationFile: "local:///opt/spark/work-dir/spark_pi.py"
  arguments: ["10000"]
  sparkVersion: "3.5.0"
  restartPolicy:
    type: Never
  driver:
    coreRequest: "200m"  # explicit request
    coreLimit: "500m"    # explicit limit > request
    memory: "512m"
    serviceAccount: spark

  executor:
    coreRequest: "200m"
    coreLimit: "500m"
    memory: "1Gi"
    serviceAccount: spark
