apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: spark-pi-example          # <-- Tên CỐ ĐỊNH, KHÔNG để generateName, và khớp với application_name trong sensor
  namespace: spark-jobs
spec:
  type: Scala
  mode: cluster
  image: "acrmlfoteaidev.azurecr.io/spark-py-job:v1"
  imagePullPolicy: Always
  mainClass: org.apache.spark.examples.SparkPi
  mainApplicationFile: "local:///opt/spark/work-dir/spark_pi.py"
  arguments: ["10000"]
  sparkVersion: "3.5.0"
  restartPolicy:
    type: Never
  driver:
    cores: 1
    coreLimit: "1200m"
    memory: "1g"
    serviceAccount: spark
  executor:
    cores: 2
    instances: 2
    memory: "2g"